//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Lobby : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LobbySnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.lobby_LobbySnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean LobbySnapTurnRight
        {
            get
            {
                return SteamVR_Actions.lobby_LobbySnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean LobbySnapTurnUp
        {
            get
            {
                return SteamVR_Actions.lobby_LobbySnapTurnUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean LobbySnapTurnDown
        {
            get
            {
                return SteamVR_Actions.lobby_LobbySnapTurnDown;
            }
        }
    }
}
