//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DrawingBoard : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean DBGrabPinch
        {
            get
            {
                return SteamVR_Actions.drawingBoard_DBGrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean DBSnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.drawingBoard_DBSnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean DBSnapTurnRight
        {
            get
            {
                return SteamVR_Actions.drawingBoard_DBSnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean DBSnapTurnUp
        {
            get
            {
                return SteamVR_Actions.drawingBoard_DBSnapTurnUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean DBSnapTurnDown
        {
            get
            {
                return SteamVR_Actions.drawingBoard_DBSnapTurnDown;
            }
        }
    }
}
