//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_WhiteBoard : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean WBSnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.whiteBoard_WBSnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean WBSnapTurnRight
        {
            get
            {
                return SteamVR_Actions.whiteBoard_WBSnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean WBSnapTurnUp
        {
            get
            {
                return SteamVR_Actions.whiteBoard_WBSnapTurnUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean WBSnapTurnDown
        {
            get
            {
                return SteamVR_Actions.whiteBoard_WBSnapTurnDown;
            }
        }
    }
}
