//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DrawingBoard : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.drawingBoard_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad
        {
            get
            {
                return SteamVR_Actions.drawingBoard_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.drawingBoard_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.drawingBoard_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.drawingBoard_SnapTurnUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.drawingBoard_SnapTurnDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.drawingBoard_Menu;
            }
        }
    }
}
