//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Lobby : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.lobby_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.lobby_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.lobby_SnapTurnUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.lobby_SnapTurnDown;
            }
        }
    }
}
