//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnUp;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnDown;
        
        private static SteamVR_Action_Boolean p_lobby_LobbySnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_lobby_LobbySnapTurnRight;
        
        private static SteamVR_Action_Boolean p_lobby_LobbySnapTurnUp;
        
        private static SteamVR_Action_Boolean p_lobby_LobbySnapTurnDown;
        
        private static SteamVR_Action_Boolean p_drawingBoard_DBGrabPinch;
        
        private static SteamVR_Action_Boolean p_drawingBoard_DBSnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_drawingBoard_DBSnapTurnRight;
        
        private static SteamVR_Action_Boolean p_drawingBoard_DBSnapTurnUp;
        
        private static SteamVR_Action_Boolean p_drawingBoard_DBSnapTurnDown;
        
        private static SteamVR_Action_Boolean p_whiteBoard_WBSnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_whiteBoard_WBSnapTurnRight;
        
        private static SteamVR_Action_Boolean p_whiteBoard_WBSnapTurnUp;
        
        private static SteamVR_Action_Boolean p_whiteBoard_WBSnapTurnDown;
        
        private static SteamVR_Action_Boolean p_roomControl_RoomSwitch;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_LobbySnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_lobby_LobbySnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_LobbySnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_lobby_LobbySnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_LobbySnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_lobby_LobbySnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_LobbySnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_lobby_LobbySnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_DBGrabPinch
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_DBGrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_DBSnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_DBSnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_DBSnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_DBSnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_DBSnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_DBSnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_DBSnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_DBSnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_WBSnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_WBSnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_WBSnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_WBSnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_WBSnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_WBSnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_WBSnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_WBSnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean roomControl_RoomSwitch
        {
            get
            {
                return SteamVR_Actions.p_roomControl_RoomSwitch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_LobbySnapTurnLeft,
                    SteamVR_Actions.lobby_LobbySnapTurnRight,
                    SteamVR_Actions.lobby_LobbySnapTurnUp,
                    SteamVR_Actions.lobby_LobbySnapTurnDown,
                    SteamVR_Actions.drawingBoard_DBGrabPinch,
                    SteamVR_Actions.drawingBoard_DBSnapTurnLeft,
                    SteamVR_Actions.drawingBoard_DBSnapTurnRight,
                    SteamVR_Actions.drawingBoard_DBSnapTurnUp,
                    SteamVR_Actions.drawingBoard_DBSnapTurnDown,
                    SteamVR_Actions.whiteBoard_WBSnapTurnLeft,
                    SteamVR_Actions.whiteBoard_WBSnapTurnRight,
                    SteamVR_Actions.whiteBoard_WBSnapTurnUp,
                    SteamVR_Actions.whiteBoard_WBSnapTurnDown,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_LobbySnapTurnLeft,
                    SteamVR_Actions.lobby_LobbySnapTurnRight,
                    SteamVR_Actions.lobby_LobbySnapTurnUp,
                    SteamVR_Actions.lobby_LobbySnapTurnDown,
                    SteamVR_Actions.drawingBoard_DBGrabPinch,
                    SteamVR_Actions.drawingBoard_DBSnapTurnLeft,
                    SteamVR_Actions.drawingBoard_DBSnapTurnRight,
                    SteamVR_Actions.drawingBoard_DBSnapTurnUp,
                    SteamVR_Actions.drawingBoard_DBSnapTurnDown,
                    SteamVR_Actions.whiteBoard_WBSnapTurnLeft,
                    SteamVR_Actions.whiteBoard_WBSnapTurnRight,
                    SteamVR_Actions.whiteBoard_WBSnapTurnUp,
                    SteamVR_Actions.whiteBoard_WBSnapTurnDown,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_LobbySnapTurnLeft,
                    SteamVR_Actions.lobby_LobbySnapTurnRight,
                    SteamVR_Actions.lobby_LobbySnapTurnUp,
                    SteamVR_Actions.lobby_LobbySnapTurnDown,
                    SteamVR_Actions.drawingBoard_DBGrabPinch,
                    SteamVR_Actions.drawingBoard_DBSnapTurnLeft,
                    SteamVR_Actions.drawingBoard_DBSnapTurnRight,
                    SteamVR_Actions.drawingBoard_DBSnapTurnUp,
                    SteamVR_Actions.drawingBoard_DBSnapTurnDown,
                    SteamVR_Actions.whiteBoard_WBSnapTurnLeft,
                    SteamVR_Actions.whiteBoard_WBSnapTurnRight,
                    SteamVR_Actions.whiteBoard_WBSnapTurnUp,
                    SteamVR_Actions.whiteBoard_WBSnapTurnDown,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_LobbySnapTurnLeft,
                    SteamVR_Actions.lobby_LobbySnapTurnRight,
                    SteamVR_Actions.lobby_LobbySnapTurnUp,
                    SteamVR_Actions.lobby_LobbySnapTurnDown,
                    SteamVR_Actions.drawingBoard_DBGrabPinch,
                    SteamVR_Actions.drawingBoard_DBSnapTurnLeft,
                    SteamVR_Actions.drawingBoard_DBSnapTurnRight,
                    SteamVR_Actions.drawingBoard_DBSnapTurnUp,
                    SteamVR_Actions.drawingBoard_DBSnapTurnDown,
                    SteamVR_Actions.whiteBoard_WBSnapTurnLeft,
                    SteamVR_Actions.whiteBoard_WBSnapTurnRight,
                    SteamVR_Actions.whiteBoard_WBSnapTurnUp,
                    SteamVR_Actions.whiteBoard_WBSnapTurnDown,
                    SteamVR_Actions.roomControl_RoomSwitch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnLeft")));
            SteamVR_Actions.p_default_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnRight")));
            SteamVR_Actions.p_default_SnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnUp")));
            SteamVR_Actions.p_default_SnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnDown")));
            SteamVR_Actions.p_lobby_LobbySnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/LobbySnapTurnLeft")));
            SteamVR_Actions.p_lobby_LobbySnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/LobbySnapTurnRight")));
            SteamVR_Actions.p_lobby_LobbySnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/LobbySnapTurnUp")));
            SteamVR_Actions.p_lobby_LobbySnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/LobbySnapTurnDown")));
            SteamVR_Actions.p_drawingBoard_DBGrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/DBGrabPinch")));
            SteamVR_Actions.p_drawingBoard_DBSnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/DBSnapTurnLeft")));
            SteamVR_Actions.p_drawingBoard_DBSnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/DBSnapTurnRight")));
            SteamVR_Actions.p_drawingBoard_DBSnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/DBSnapTurnUp")));
            SteamVR_Actions.p_drawingBoard_DBSnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/DBSnapTurnDown")));
            SteamVR_Actions.p_whiteBoard_WBSnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/WBSnapTurnLeft")));
            SteamVR_Actions.p_whiteBoard_WBSnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/WBSnapTurnRight")));
            SteamVR_Actions.p_whiteBoard_WBSnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/WBSnapTurnUp")));
            SteamVR_Actions.p_whiteBoard_WBSnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/WBSnapTurnDown")));
            SteamVR_Actions.p_roomControl_RoomSwitch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/RoomControl/in/RoomSwitch")));
        }
    }
}
