//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnUp;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnDown;
        
        private static SteamVR_Action_Boolean p_lobby_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_lobby_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_lobby_SnapTurnUp;
        
        private static SteamVR_Action_Boolean p_lobby_SnapTurnDown;
        
        private static SteamVR_Action_Boolean p_drawingBoard_GrabPinch;
        
        private static SteamVR_Action_Boolean p_drawingBoard_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_drawingBoard_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_drawingBoard_SnapTurnUp;
        
        private static SteamVR_Action_Boolean p_drawingBoard_SnapTurnDown;
        
        private static SteamVR_Action_Boolean p_whiteBoard_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_whiteBoard_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_whiteBoard_SnapTurnUp;
        
        private static SteamVR_Action_Boolean p_roomControl_RoomSwitch;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_lobby_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_lobby_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_lobby_SnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lobby_SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_lobby_SnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_SnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean drawingBoard_SnapTurnDown
        {
            get
            {
                return SteamVR_Actions.p_drawingBoard_SnapTurnDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean whiteBoard_SnapTurnUp
        {
            get
            {
                return SteamVR_Actions.p_whiteBoard_SnapTurnUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean roomControl_RoomSwitch
        {
            get
            {
                return SteamVR_Actions.p_roomControl_RoomSwitch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_SnapTurnLeft,
                    SteamVR_Actions.lobby_SnapTurnRight,
                    SteamVR_Actions.lobby_SnapTurnUp,
                    SteamVR_Actions.lobby_SnapTurnDown,
                    SteamVR_Actions.drawingBoard_GrabPinch,
                    SteamVR_Actions.drawingBoard_SnapTurnLeft,
                    SteamVR_Actions.drawingBoard_SnapTurnRight,
                    SteamVR_Actions.drawingBoard_SnapTurnUp,
                    SteamVR_Actions.drawingBoard_SnapTurnDown,
                    SteamVR_Actions.whiteBoard_SnapTurnLeft,
                    SteamVR_Actions.whiteBoard_SnapTurnRight,
                    SteamVR_Actions.whiteBoard_SnapTurnUp,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_SnapTurnLeft,
                    SteamVR_Actions.lobby_SnapTurnRight,
                    SteamVR_Actions.lobby_SnapTurnUp,
                    SteamVR_Actions.lobby_SnapTurnDown,
                    SteamVR_Actions.drawingBoard_GrabPinch,
                    SteamVR_Actions.drawingBoard_SnapTurnLeft,
                    SteamVR_Actions.drawingBoard_SnapTurnRight,
                    SteamVR_Actions.drawingBoard_SnapTurnUp,
                    SteamVR_Actions.drawingBoard_SnapTurnDown,
                    SteamVR_Actions.whiteBoard_SnapTurnLeft,
                    SteamVR_Actions.whiteBoard_SnapTurnRight,
                    SteamVR_Actions.whiteBoard_SnapTurnUp,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_SnapTurnLeft,
                    SteamVR_Actions.lobby_SnapTurnRight,
                    SteamVR_Actions.lobby_SnapTurnUp,
                    SteamVR_Actions.lobby_SnapTurnDown,
                    SteamVR_Actions.drawingBoard_GrabPinch,
                    SteamVR_Actions.drawingBoard_SnapTurnLeft,
                    SteamVR_Actions.drawingBoard_SnapTurnRight,
                    SteamVR_Actions.drawingBoard_SnapTurnUp,
                    SteamVR_Actions.drawingBoard_SnapTurnDown,
                    SteamVR_Actions.whiteBoard_SnapTurnLeft,
                    SteamVR_Actions.whiteBoard_SnapTurnRight,
                    SteamVR_Actions.whiteBoard_SnapTurnUp,
                    SteamVR_Actions.roomControl_RoomSwitch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_SnapTurnUp,
                    SteamVR_Actions.default_SnapTurnDown,
                    SteamVR_Actions.lobby_SnapTurnLeft,
                    SteamVR_Actions.lobby_SnapTurnRight,
                    SteamVR_Actions.lobby_SnapTurnUp,
                    SteamVR_Actions.lobby_SnapTurnDown,
                    SteamVR_Actions.drawingBoard_GrabPinch,
                    SteamVR_Actions.drawingBoard_SnapTurnLeft,
                    SteamVR_Actions.drawingBoard_SnapTurnRight,
                    SteamVR_Actions.drawingBoard_SnapTurnUp,
                    SteamVR_Actions.drawingBoard_SnapTurnDown,
                    SteamVR_Actions.whiteBoard_SnapTurnLeft,
                    SteamVR_Actions.whiteBoard_SnapTurnRight,
                    SteamVR_Actions.whiteBoard_SnapTurnUp,
                    SteamVR_Actions.roomControl_RoomSwitch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnLeft")));
            SteamVR_Actions.p_default_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnRight")));
            SteamVR_Actions.p_default_SnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnUp")));
            SteamVR_Actions.p_default_SnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnDown")));
            SteamVR_Actions.p_lobby_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/SnapTurnLeft")));
            SteamVR_Actions.p_lobby_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/SnapTurnRight")));
            SteamVR_Actions.p_lobby_SnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/SnapTurnUp")));
            SteamVR_Actions.p_lobby_SnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Lobby/in/SnapTurnDown")));
            SteamVR_Actions.p_drawingBoard_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/GrabPinch")));
            SteamVR_Actions.p_drawingBoard_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/SnapTurnLeft")));
            SteamVR_Actions.p_drawingBoard_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/SnapTurnRight")));
            SteamVR_Actions.p_drawingBoard_SnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/SnapTurnUp")));
            SteamVR_Actions.p_drawingBoard_SnapTurnDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DrawingBoard/in/SnapTurnDown")));
            SteamVR_Actions.p_whiteBoard_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/SnapTurnLeft")));
            SteamVR_Actions.p_whiteBoard_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/SnapTurnRight")));
            SteamVR_Actions.p_whiteBoard_SnapTurnUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/WhiteBoard/in/SnapTurnUp")));
            SteamVR_Actions.p_roomControl_RoomSwitch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/RoomControl/in/RoomSwitch")));
        }
    }
}
